apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  destination:
    name: ''
    namespace: default"
    server: 'https://kubernetes.default.svc'
  source:
    path: HelmChart
    repoURL: 'https://github.com/Goodkatt/qlub-beautified.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: dev-projects
  syncPolicy:
    automated:
      prune: false
      selfHeal: true