apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Goodkatt/qlub-beautified.git
    targetRevision: asd
    path: HelmChart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  valueFiles:
    - values.yaml
